version: 2.1

jobs:
  unit:
    environment:
      DBT_INVOCATION_ENV: circle
    docker:
      - image: fishtownanalytics/test-container:10
    steps:
      - checkout
      - run: tox -e flake8,unit

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
